spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/attendancedb}
spring.datasource.username=${DB_USERNAME:attendance}
spring.datasource.password=${DB_PASSWORD:attendance}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update